name: Actions-Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
      - name: List Files
        run: |
          pwd
          ls
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Saikumar
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"